### PR TITLE
Pre-commit hooks and relevant README

### PR DESCRIPTION
**Pull request by 2000yeshu**
- Added Developing section in README for setting up pre-commit hooks for the local repo.
- Added .pre-commit-config.yaml

### CODE REVIEW

**Review by ghostwriternr — CHANGES_REQUESTED** [review]
Hello @2000yeshu! No apology can be enough for the delay in responding. Thanks for being patient and for this super useful PR! The changes look great to me.

I didn't have much luck getting it to work though.
```
/Users/nareshr/.cache/pre-commit/repo_13nciwu/py_env-python3.8/lib/python3.8/site-packages/isort/main.py:104: UserWarning: Unable to parse file --skip migrations due to [Errno 2] No such file or directory: '/Users/nareshr/github/lttkgp/C-3PO/--skip migrations'
  warn(f"Unable to parse file {file_name} due to {error}")
Fixing /Users/nareshr/github/lttkgp/C-3PO/c3po/manage.py
```

I'll investigate the issue in a bit too. If you know the fix too, I'd be happy to quickly review it!

**Comment by mukul-mehta** [comment]
I had the same error, seems like it isn't parsing args for `isort` correctly. There is no space between `./` and the arguments. A simple fix for me was adding a space after `./` 

```
- repo: https://github.com/timothycrosley/isort
    rev: 5.0.5
    hooks:
      - id: isort
        files: "./ "
        args: ["--atomic", "--skip migrations"]
```

**Comment by 2000yeshu** [comment]
That's wierd..It didn't came up before. I'll make that change.

**Review by 2000yeshu — COMMENTED** [review]
I have added the space as indicated by @mukul-mehta. Also what type of changes are you making to test each type of hook.

**Review by ghostwriternr — APPROVED** [review]
Looks A-OK now 🎉

**Comment by ghostwriternr** [comment]
> Also what type of changes are you making to test each type of hook
Some simple changes to `manage.py` covered several of these hooks. There isn't any need to test the hooks themselves (since the library has done that for us), but rather just to confirm that every hook that we have included runs as expected.

**Pull request merged**
